webhook_url: https://discordapp.com/api/webhooks/903431994136989716/0ebBeTIkuJ44ck7ooeEDwE_nJ-N0masFQ9-eIyrwnBAqKAPsXspkBHOQZyHbfh_Fh7Jh

channel_ids: ['UCoSrY_IQQVpmIRZ9Xf-y93g', 'UCMwGHR0BTZuLsmjY_NT5Pwg','UCyl1z3jo3XHR1riLFKG5UAg', 'UC8rcEBzJSleTkf_-agPM20g', 'UCL_qhgtOy0dy1Agp8vkySQg', 'UCmbs8T6MWqUHP1tIQvSgKrg', 'UC3n5uGu18FoCy23ggWWp8tA', 'UCsUj0dszADCGbF3gNrQEuSQ', 'UCO_aKKYxn4tvrqPjcTzZ6EQ', 'UCgmPnx-EEeOrZSg5Tiw7ZRQ']

message_prefix: A new video has just gone live!